package exceptions;

import java.util.Scanner;

public class Finally {
  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);

    // Generated by IntelliJ
    try (scanner) {
      try {
        System.out.println(7 / scanner.nextInt());
      } catch (Exception e) {
        System.out.println(e.getMessage());
      } finally {
        System.out.println("Finally #01");
      }
      System.out.println(7 / scanner.nextInt());
    } finally {
      System.out.println("Finally #02");
    }

    // Original One
//    try {
//      System.out.println(7 / scanner.nextInt());
//    } catch (Exception e) {
//      System.out.println(e.getMessage());
//    } finally {
//      System.out.println("Finally #01");
//    }
//
//    try {
//      System.out.println(7 / scanner.nextInt());
//    } finally {
//      System.out.println("Finally #02");
//      scanner.close();
//    }

    System.out.println("End.");
  }
}
